export const students = [
  { roll: 1, name: "MOHAMMAD TAREK MUNAIM", gender: "Male" },
  { roll: 2, name: "TOTULUR RAHMAN", gender: "Male" },
  { roll: 3, name: "MD. RAKIBUL ISLAM", gender: "Male" },
  { roll: 4, name: "TAMANNA AKTER", gender: "Female" },
  { roll: 5, name: "ABUL BAYEAN", gender: "Male" },
  { roll: 6, name: "IBRAHIM KHOLIL AKANDA", gender: "Male" },
  { roll: 7, name: "MD. SHAHIN", gender: "Male" },
  { roll: 8, name: "MD. NAFIZ AHMED RIAD", gender: "Male" },
  { roll: 9, name: "MD. JONAYET HOSSEN MOMAN", gender: "Male" },
  { roll: 10, name: "MD. ANGKON SHEIKH", gender: "Male" },
  { roll: 11, name: "PRANTO BISWAS", gender: "Male" },
  { roll: 12, name: "MD. SHIHAB UDDIN", gender: "Male" },
  { roll: 13, name: "MD. RUBAITUL ISLAM HEMEL", gender: "Male" },
  { roll: 14, name: "FEROZ MAHMUD", gender: "Male" },
  { roll: 15, name: "MD. RIYAZ AHMED RIMON", gender: "Male" },
  { roll: 16, name: "MOHAMMAD SHAHIDULLAH SHAHED", gender: "Male" },
  { roll: 17, name: "MD. HOSSAIN KABIR", gender: "Male" },
  { roll: 18, name: "MUHAMMED TANJIM", gender: "Male" },
  { roll: 19, name: "KAWSAR AHAMED IFRAT", gender: "Male" },
  { roll: 20, name: "MD. RIMON ISLAM", gender: "Male" },
  { roll: 21, name: "MST. LIZA AKTER", gender: "Female" },
  { roll: 22, name: "BIJOYA BARMAN MUKTA", gender: "Female" },
  { roll: 23, name: "NUSRAT JAHAN EVA", gender: "Female" },
  { roll: 24, name: "MAKSUDA AKTHER", gender: "Female" },
  { roll: 25, name: "SHADNAN RAHMAN FAHIM", gender: "Male" },
  { roll: 26, name: "MD. TAMIM HOSSEN", gender: "Male" },
  { roll: 27, name: "SOMIT SARKAR SUJOY", gender: "Male" },
  { roll: 28, name: "MD. FAHAD MAHMUD", gender: "Male" },
  { roll: 29, name: "MD. KAYES MIAH", gender: "Male" },
  { roll: 30, name: "SAYEED HASAN SHUVO", gender: "Male" },
  { roll: 31, name: "DIP KARATI", gender: "Male" },
  { roll: 32, name: "MD. SAGOR", gender: "Male" },
  { roll: 33, name: "MD. MAHIM HOSSAIN", gender: "Male" },
  { roll: 34, name: "MD. ARIFUL ISLAM", gender: "Male" },
  { roll: 35, name: "HARUNUR RASHID ZABER", gender: "Male" },
  { roll: 36, name: "FARDIN ISLAM FOUAD", gender: "Male" },
  { roll: 37, name: "KARIMA AKTER", gender: "Female" },
  { roll: 38, name: "YASIR ARAFAT ALIF", gender: "Male" },
  { roll: 39, name: "SHORIF MIA", gender: "Male" },
  { roll: 40, name: "OALID LASKAR JOY", gender: "Male" },
  { roll: 41, name: "MD. ABDUR RAHMAN RIAD", gender: "Male" },
  { roll: 42, name: "MD. RIYADUL ISLAM RIFAT", gender: "Male" },
  { roll: 43, name: "MD. MASUM AHAMMED SHADHIN", gender: "Male" },
  { roll: 44, name: "MD. HRIDOY MIAH", gender: "Male" },
  { roll: 45, name: "TAMIM IQBAL", gender: "Male" },
  { roll: 46, name: "SOUROV DEBNATH SHASSO", gender: "Male" },
  { roll: 47, name: "MD.RIFAT AHMED SHAFIN", gender: "Male" },
  { roll: 48, name: "S. M. FATIN FUAD", gender: "Male" },
  { roll: 49, name: "MD. AL MOJAHID", gender: "Male" },
  { roll: 50, name: "SALMAN SHIHAB RATUL", gender: "Male" },
];
